services:
  database:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: employment
      POSTGRES_USER: observer_user
      POSTGRES_PASSWORD: qwerty2F

    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
