services:
  database:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: employment
      POSTGRES_USER: observer_user
      POSTGRES_PASSWORD: qwerty2F

    volumes:
      - pgdata:/var/lib/postgresql/data
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3.8-management
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./backend/.env

  worker:
    container_name: celery
    hostname: celery
    build: ./backend
    volumes:
      - ./backend:/backend
    command: celery -A project.celery_app worker -l INFO
    links:
      - rabbitmq
    depends_on:
      - database
      - rabbitmq
    env_file:
      - ./backend/.env


volumes:
  pgdata:
