# Generated by Django 5.0.6 on 2024-10-23 13:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('additional_id', models.IntegerField(verbose_name='Персональный идентификатор пользователя')),
                ('customer_name', models.CharField(max_length=150, verbose_name='ФИО/Сокращенное название')),
                ('customer_type', models.CharField(choices=[('CM', 'Физическое лицо'), ('LC', 'ООО'), ('IE', 'Индивидуальный предприниматель')], max_length=2)),
                ('post_address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Почтовый адрес')),
                ('inn', models.CharField(blank=True, null=True, verbose_name='Идентификационный номер налогоплательщика')),
                ('full_company_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Полное название компании')),
                ('orgn', models.CharField(blank=True, max_length=150, null=True, verbose_name='Основной гос. регистрационный номер')),
                ('kpp', models.CharField(blank=True, max_length=150, null=True, verbose_name='Код причины постановки на учет')),
                ('legal_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Юридический адрес')),
                ('okpo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Общероссийский классификатор предприятий и организаций')),
                ('okved', models.CharField(blank=True, max_length=255, null=True, verbose_name='Общероссийский классификатор видов экономической деятельности')),
                ('place_of_residence', models.CharField(blank=True, max_length=150, null=True, verbose_name='Адрес прописки')),
                ('ogrnip', models.CharField(blank=True, null=True, verbose_name='Основной государственный регистрационный номер индивидуального предпринимателя')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
                'ordering': ['additional_id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerContacts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_name', models.CharField(max_length=150, null=True, verbose_name='Имя контактного лица (может быть не сам заказчик)')),
                ('contact_type', models.CharField(choices=[('PH', 'Телефон'), ('EL', 'Электронная почта'), ('TG', 'Аккаунт Телеграм'), ('WA', "Аккаунт What's App"), ('CS', 'Сайт заказчика')], max_length=2, verbose_name='Тип контакта')),
                ('contact_info', models.CharField(max_length=255, verbose_name='Данные контакта')),
            ],
            options={
                'verbose_name': 'Контакт заказчика',
                'verbose_name_plural': 'Контакты заказчика',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerPassport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('series', models.CharField(max_length=150, verbose_name='Серия паспорта')),
                ('number', models.CharField(max_length=150, verbose_name='Номер паспорта')),
                ('release_date', models.DateField(max_length=150, verbose_name='Дата выдачи')),
                ('issued', models.CharField(max_length=150, verbose_name='Выдан')),
                ('unit_code', models.CharField(max_length=7, verbose_name='Код подразделения')),
            ],
            options={
                'verbose_name': 'Паспорт заказчика',
                'verbose_name_plural': 'Паспорта заказчиков',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerRequisites',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(max_length=150, verbose_name='Название банка')),
                ('bic', models.CharField(max_length=150, verbose_name='Банковский идентификационный код')),
                ('bank_account', models.CharField(max_length=150, verbose_name='Корреспондентский счет банка')),
                ('customer_account_number', models.CharField(max_length=150, verbose_name='Номер расчетного счета заказчика')),
            ],
            options={
                'verbose_name': 'Реквизит заказчика',
                'verbose_name_plural': 'Реквизиты заказчика',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
    ]
