# Generated by Django 5.0.6 on 2024-05-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['additional_id'], 'verbose_name': 'Заказчик', 'verbose_name_plural': 'Заказчики'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='additional_id',
            field=models.IntegerField(verbose_name='Персональный идентификатор пользователя'),
        ),
    ]
