# Generated by Django 5.0.6 on 2024-10-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('COMMON', 'Физическое лицо'), ('LLC', 'ООО'), ('IE', 'Индивидуальный предприниматель')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customercontacts',
            name='contact_type',
            field=models.CharField(choices=[('PHONE', 'Телефон'), ('EMAIL', 'Электронная почта'), ('TELEGRAM', 'Аккаунт Телеграм'), ('WHATSAPP', "Аккаунт What's App"), ('CUSTOMERSITE', 'Сайт заказчика')], max_length=20, verbose_name='Тип контакта'),
        ),
    ]
