# Generated by Django 5.0.6 on 2024-06-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customerrequisites_options_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='inn',
            field=models.CharField(verbose_name='Идентификационный номер налогоплательщика'),
        ),
    ]
