# Generated by Django 5.0.6 on 2025-05-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_customer_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('COMMON', 'Физическое лицо'), ('LLC', 'ООО'), ('IE', 'Индивидуальный предприниматель')], max_length=20, verbose_name='Тип заказчика'),
        ),
    ]
