# Generated by Django 5.0.6 on 2024-06-07 10:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_inn'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='full_company_name',
            field=models.CharField(default=None, max_length=150, null=True, verbose_name='Полное название компании'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='inn',
            field=models.CharField(default=None, null=True, verbose_name='Идентификационный номер налогоплательщика'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='kpp',
            field=models.CharField(default=None, max_length=150, null=True, verbose_name='Код причины постановки на учет'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='legal_address',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='okpo',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Общероссийский классификатор предприятий и организаций'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='okved',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Общероссийский классификатор видов экономической деятельности'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='orgn',
            field=models.CharField(default=None, max_length=150, null=True, verbose_name='Основной гос. регистрационный номер'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='post_address',
            field=models.CharField(default=None, max_length=150, null=True, verbose_name='Почтовый адрес'),
        ),
        migrations.AlterField(
            model_name='customercontacts',
            name='contact_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Имя контактного лица (может быть не сам заказчик)'),
        ),
        migrations.AlterField(
            model_name='customerrequisites',
            name='bic',
            field=models.CharField(max_length=150, verbose_name='Банковский идентификационный код'),
        ),
        migrations.AlterField(
            model_name='customerrequisites',
            name='customer_account_number',
            field=models.CharField(max_length=150, verbose_name='Номер расчетного счета заказчика'),
        ),
    ]
