# Generated by Django 5.0.6 on 2024-06-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='full_company_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Полное название компании'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='inn',
            field=models.CharField(blank=True, null=True, verbose_name='Идентификационный номер налогоплательщика'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='kpp',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Код причины постановки на учет'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='legal_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ogrnip',
            field=models.CharField(blank=True, null=True, verbose_name='Основной государственный регистрационный номер индивидуального предпринимателя'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='okpo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Общероссийский классификатор предприятий и организаций'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='okved',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Общероссийский классификатор видов экономической деятельности'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='orgn',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Основной гос. регистрационный номер'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='place_of_residence',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Адрес прописки'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='post_address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Почтовый адрес'),
        ),
    ]
