# Generated by Django 5.0.6 on 2024-07-09 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_alter_customercontacts_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('series', models.CharField(max_length=150, verbose_name='Серия паспорта')),
                ('number', models.CharField(max_length=150, verbose_name='Номер паспорта')),
                ('release_date', models.DateField(max_length=150, verbose_name='Дата выдачи')),
                ('issued', models.CharField(max_length=150, verbose_name='Выдан')),
                ('unit_code', models.CharField(max_length=7, verbose_name='Код подразделения')),
                ('customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='customers.customer', verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Паспорт заказчика',
                'verbose_name_plural': 'Паспорта заказчиков',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
    ]
