{
 "title": "Django monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Infra",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  { "title": "Requests and Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "HTTP Requests per Second",
   "type": "timeseries",
   "description": "HTTP Requests per Second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "rate(django_http_requests_total_by_method_total[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "HTTP Latency p95/p99",
   "type": "timeseries",
   "description": "HTTP Latency p95/p99",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\r\n  sum(rate(django_http_requests_latency_seconds_by_view_method_bucket[1m]))\r\n  by (le)\r\n)",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99,\r\n  sum(rate(django_http_requests_latency_seconds_by_view_method_bucket[1m]))\r\n  by (le)\r\n)",
     "legendFormat": "p99"
    }
   ]
  },
  { "title": "Models Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Model Inserts Per Second",
   "type": "timeseries",
   "description": "Model Inserts Per Second",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(django_model_updates_total[1m])",
     "legendFormat": "{{model}}"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Model Updates Per Second",
   "type": "timeseries",
   "description": "Model Updates Per Second",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(django_model_updates_total[1m])",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Model Deletes Per Second",
   "type": "timeseries",
   "description": "Model Deletes Per Second",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(django_model_deletes_total[1m])",
     "legendFormat": "{{model}}"
    }
   ]
  }
 ]
}