# Generated by Django 5.0.6 on 2024-05-29 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='act',
            options={'verbose_name': 'Акт', 'verbose_name_plural': 'Акты'},
        ),
        migrations.AlterModelOptions(
            name='additional',
            options={'verbose_name': 'Дополнение к договору', 'verbose_name_plural': 'Дополнения к договору'},
        ),
        migrations.AlterModelOptions(
            name='agreement',
            options={'verbose_name': 'Договор', 'verbose_name_plural': 'Договоры'},
        ),
        migrations.AlterModelOptions(
            name='checkmodel',
            options={'verbose_name': 'Чек', 'verbose_name_plural': 'Чеки'},
        ),
    ]
