# Generated by Django 5.0.6 on 2024-06-07 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_act_options_alter_additional_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseattachment',
            name='additional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_attachment', to='documents.additional'),
        ),
        migrations.AlterField(
            model_name='baseattachment',
            name='agreement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_attachment', to='documents.agreement'),
        ),
    ]
