# Generated by Django 5.0.6 on 2024-10-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создан'), ('CLOSED', 'Закрыт')], default='CREATED', max_length=20, verbose_name='Статус акта'),
        ),
        migrations.AlterField(
            model_name='additional',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создан'), ('CLOSED', 'Закрыт')], default='CREATED', max_length=20, verbose_name='Статус Дополнения'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создан'), ('SIGNED', 'Подписан'), ('CLOSED', 'Закрыт'), ('DISSOLVED', 'Расторгнут'), ('EXPIRED', 'Истек')], default='CREATED', max_length=20, verbose_name='Статус договора'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создан'), ('CLOSED', 'Закрыт')], default='CREATED', max_length=20, verbose_name='Статус счета'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Инициирован'), ('CLOSED', 'Проведен')], default='INITIATED', max_length=20, verbose_name='Статус счета'),
        ),
        migrations.AlterField(
            model_name='usertemplate',
            name='template_type',
            field=models.CharField(choices=[('AGREEMENT', 'Договор'), ('ADDITIONAL', 'Дополнение к договору'), ('ACT', 'Акт'), ('CHECK', 'Чек'), ('INVOICES', 'Счет')], max_length=20, verbose_name='Тип шаблона'),
        ),
    ]
