# Generated by Django 5.0.6 on 2025-05-10 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_customer_type'),
        ('documents', '0003_alter_act_status_alter_additional_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='customers.customer', verbose_name='Заказчик'),
        ),
    ]
