# Generated by Django 5.0.6 on 2024-06-10 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_baseattachment_additional_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('baseattachment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.baseattachment')),
                ('amount', models.IntegerField(verbose_name='Сумма счета')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счет',
            },
            bases=('documents.baseattachment',),
        ),
        migrations.AlterField(
            model_name='checkmodel',
            name='amount',
            field=models.IntegerField(verbose_name='Сумма чека'),
        ),
    ]
