# Generated by Django 5.0.6 on 2024-06-12 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_invoice_alter_checkmodel_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseattachment',
            name='additional',
        ),
        migrations.RemoveField(
            model_name='baseattachment',
            name='agreement',
        ),
        migrations.RemoveField(
            model_name='checkmodel',
            name='baseattachment_ptr',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='baseattachment_ptr',
        ),
        migrations.DeleteModel(
            name='Act',
        ),
        migrations.DeleteModel(
            name='CheckModel',
        ),
        migrations.DeleteModel(
            name='BaseAttachment',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
