# Generated by Django 5.0.6 on 2024-06-12 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_remove_baseattachment_additional_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.additional')),
                ('agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.agreement')),
            ],
        ),
        migrations.CreateModel(
            name='Act',
            fields=[
                ('baseattachment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.baseattachment')),
                ('title', models.CharField(max_length=150, verbose_name='Название акта')),
                ('content', models.TextField(verbose_name='Текст акта')),
            ],
            options={
                'verbose_name': 'Акт',
                'verbose_name_plural': 'Акты',
            },
            bases=('documents.baseattachment',),
        ),
        migrations.CreateModel(
            name='CheckModel',
            fields=[
                ('baseattachment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.baseattachment')),
                ('amount', models.IntegerField(verbose_name='Сумма чека')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
            },
            bases=('documents.baseattachment',),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('baseattachment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.baseattachment')),
                ('amount', models.IntegerField(verbose_name='Сумма счета')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
            },
            bases=('documents.baseattachment',),
        ),
    ]
