# Generated by Django 5.0.6 on 2024-06-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_baseattachment_act_checkmodel_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='baseattachment',
            name='additional',
        ),
        migrations.RemoveField(
            model_name='baseattachment',
            name='agreement',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='baseattachment_ptr',
        ),
        migrations.RemoveField(
            model_name='checkmodel',
            name='baseattachment_ptr',
        ),
        migrations.DeleteModel(
            name='Act',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='BaseAttachment',
        ),
        migrations.DeleteModel(
            name='CheckModel',
        ),
    ]
