# Generated by Django 5.0.6 on 2024-06-12 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_act_checkmodel_invoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomModel',
        ),
        migrations.AlterField(
            model_name='act',
            name='additional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acts', to='documents.additional'),
        ),
        migrations.AlterField(
            model_name='act',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acts', to='documents.agreement'),
        ),
    ]
