# Generated by Django 5.0.6 on 2024-06-23 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_act_created_at_act_updated_at_additional_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='status',
            field=models.CharField(choices=[('CR', 'Создан'), ('CL', 'Закрыт')], default='CR', max_length=2, verbose_name='Статус акта'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='status',
            field=models.CharField(choices=[('CR', 'Создан'), ('SG', 'Подписан'), ('CL', 'Закрыт'), ('DS', 'Расторгнут'), ('EX', 'Истек')], default='CR', max_length=2, verbose_name='Статус договора'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('CR', 'Создан'), ('CL', 'Закрыт')], default='CR', max_length=2, verbose_name='Статус счета'),
        ),
        migrations.AlterField(
            model_name='checkmodel',
            name='additional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='documents.additional'),
        ),
        migrations.AlterField(
            model_name='checkmodel',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='documents.agreement'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='additional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='documents.additional'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='documents.agreement'),
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_type', models.CharField(max_length=150, verbose_name='Вид сделки')),
                ('amount', models.IntegerField(verbose_name='Сумма сделки')),
                ('service_date', models.DateField(verbose_name='Дата заключения сделки')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='documents.agreement', verbose_name='Договор')),
            ],
            options={
                'ordering': ['updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150, verbose_name='Название шаблона')),
                ('template_type', models.CharField(choices=[('AG', 'Договор'), ('AD', 'Дополнение к договору'), ('AC', 'Акт'), ('CH', 'Чек'), ('IN', 'Счет')], max_length=2, verbose_name='Тип шаблона')),
                ('content', models.TextField(verbose_name='Тело шаблона')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'ordering': ['updated_at'],
                'abstract': False,
            },
        ),
    ]
