# Generated by Django 5.0.6 on 2024-06-23 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_act_status_agreement_status_invoice_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='act',
            options={'ordering': ['updated_at'], 'verbose_name': 'Акт', 'verbose_name_plural': 'Акты'},
        ),
        migrations.AlterModelOptions(
            name='additional',
            options={'ordering': ['updated_at'], 'verbose_name': 'Дополнение к договору', 'verbose_name_plural': 'Дополнения к договору'},
        ),
        migrations.AlterModelOptions(
            name='agreement',
            options={'ordering': ['updated_at'], 'verbose_name': 'Договор', 'verbose_name_plural': 'Договоры'},
        ),
        migrations.AlterModelOptions(
            name='checkmodel',
            options={'ordering': ['updated_at'], 'verbose_name': 'Чек', 'verbose_name_plural': 'Чеки'},
        ),
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ['updated_at'], 'verbose_name': 'Сделка', 'verbose_name_plural': 'Сделки'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['updated_at'], 'verbose_name': 'Счет', 'verbose_name_plural': 'Счета'},
        ),
        migrations.AlterModelOptions(
            name='usertemplate',
            options={'ordering': ['updated_at'], 'verbose_name': 'Шаблон пользователя', 'verbose_name_plural': 'Шаблоны пользователя'},
        ),
    ]
