# Generated by Django 5.0.6 on 2024-06-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='number',
            field=models.CharField(default=1, max_length=16, verbose_name='Номер Акта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='additional',
            name='number',
            field=models.CharField(default=1, max_length=16, verbose_name='Номер Дополнения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkmodel',
            name='number',
            field=models.CharField(default=1, max_length=16, verbose_name='Номер Чека'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='number',
            field=models.CharField(default=1, max_length=16, verbose_name='Номер Счета'),
            preserve_default=False,
        ),
    ]
