# Generated by Django 5.0.6 on 2024-06-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_act_number_additional_number_checkmodel_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agreement',
            old_name='agreement_number',
            new_name='number',
        ),
        migrations.AddField(
            model_name='agreement',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания договора'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заключения договора'),
        ),
    ]
