# Generated by Django 5.0.6 on 2024-06-27 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_rename_agreement_number_agreement_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='act',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='documents.act', verbose_name='Акт'),
        ),
        migrations.AddField(
            model_name='payment',
            name='additional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='documents.additional', verbose_name='Дополнение'),
        ),
        migrations.AddField(
            model_name='payment',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='documents.agreement', verbose_name='Договор'),
        ),
        migrations.AddField(
            model_name='payment',
            name='check_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='documents.checkmodel', verbose_name='Чек'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='documents.invoice', verbose_name='Счет'),
        ),
        migrations.AlterField(
            model_name='act',
            name='number',
            field=models.CharField(max_length=160, verbose_name='Номер Акта'),
        ),
        migrations.AlterField(
            model_name='additional',
            name='number',
            field=models.CharField(max_length=160, verbose_name='Номер Дополнения'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='number',
            field=models.CharField(max_length=150, verbose_name='Номер договора'),
        ),
        migrations.AlterField(
            model_name='checkmodel',
            name='number',
            field=models.CharField(max_length=160, verbose_name='Номер Чека'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(max_length=160, verbose_name='Номер Счета'),
        ),
    ]
