# Generated by Django 5.0.6 on 2024-07-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_payment_act_payment_additional_payment_agreement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additional',
            name='deal_amount',
            field=models.IntegerField(default=0, verbose_name='Сумма сделки'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='deal_amount',
            field=models.IntegerField(default=0, verbose_name='Сумма сделки'),
        ),
        migrations.DeleteModel(
            name='Deal',
        ),
    ]
