# Generated by Django 5.0.6 on 2024-07-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0019_additional_deal_amount_agreement_deal_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additional',
            name='status',
            field=models.CharField(choices=[('CR', 'Создан'), ('CL', 'Закрыт')], default='CR', max_length=2, verbose_name='Статус Дополнения'),
        ),
    ]
