# Generated by Django 5.0.6 on 2024-07-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_additional_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('IN', 'Инициирован'), ('CL', 'Проведен')], default='IN', max_length=2, verbose_name='Статус счета'),
        ),
    ]
