# Generated by Django 5.0.6 on 2024-05-29 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertiseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utm_source', models.CharField()),
                ('utm_content', models.CharField()),
                ('utm_medium', models.CharField()),
                ('utm_term', models.CharField()),
                ('utm_campaign', models.CharField()),
            ],
            options={
                'verbose_name': 'Пакет рекламной информации',
                'verbose_name_plural': 'Пакеты рекламной информации',
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.IntegerField(verbose_name='Серия паспорта')),
                ('number', models.IntegerField(verbose_name='Номер паспорта')),
                ('release_date', models.DateField(verbose_name='Дата выдачи')),
                ('unit_code', models.CharField(max_length=7, verbose_name='Код подразделения')),
            ],
            options={
                'verbose_name': 'Паспорт',
                'verbose_name_plural': 'Паспорта',
            },
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='advertise',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.advertiseinfo', verbose_name='Рекламная информация'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='passport',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.passport', verbose_name='Паспорт'),
        ),
        migrations.CreateModel(
            name='UserRequisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=150, verbose_name='Название банка')),
                ('bic', models.IntegerField(verbose_name='Банковский идентификационный код')),
                ('bank_account', models.CharField(max_length=150, verbose_name='Корреспондентский счет банка')),
                ('user_account', models.CharField(max_length=150, verbose_name='Счет пользователя в банке')),
                ('card_number', models.IntegerField(verbose_name='Номер карты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Реквизит пользователя',
                'verbose_name_plural': 'Реквизиты пользователя',
            },
        ),
    ]
