# Generated by Django 5.0.6 on 2024-06-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='number',
            field=models.CharField(verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='series',
            field=models.CharField(verbose_name='Серия паспорта'),
        ),
        migrations.AlterField(
            model_name='userrequisites',
            name='card_number',
            field=models.CharField(verbose_name='Номер карты'),
        ),
    ]
