# Generated by Django 5.0.6 on 2024-06-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_middle_name_alter_passport_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiseinfo',
            name='partner_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userrequisites',
            name='bic',
            field=models.CharField(max_length=150, verbose_name='Банковский идентификационный код'),
        ),
        migrations.AlterField(
            model_name='userrequisites',
            name='card_number',
            field=models.CharField(max_length=150, verbose_name='Номер карты'),
        ),
    ]
