# Generated by Django 5.0.6 on 2024-06-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_middle_name_alter_passport_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='', max_length=150, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='passport',
            name='issued',
            field=models.CharField(default='unknown', max_length=150, verbose_name='Выдан'),
            preserve_default=False,
        ),
    ]
