# Generated by Django 5.0.6 on 2024-06-12 14:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_phone_number_passport_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passport',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
