# Generated by Django 5.0.6 on 2024-06-13 11:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_passport_created_at_passport_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='passport',
            unique_together={('series', 'number')},
        ),
        migrations.AddField(
            model_name='advertiseinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertiseinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userrequisites',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrequisites',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='passport',
            name='is_deleted',
        ),
    ]
