# Generated by Django 5.0.6 on 2024-06-23 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_passport_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertiseinfo',
            options={'ordering': ['updated_at'], 'verbose_name': 'Пакет рекламной информации', 'verbose_name_plural': 'Пакеты рекламной информации'},
        ),
        migrations.AlterModelOptions(
            name='passport',
            options={'ordering': ['updated_at'], 'verbose_name': 'Паспорт', 'verbose_name_plural': 'Паспорта'},
        ),
        migrations.AlterModelOptions(
            name='userrequisites',
            options={'ordering': ['updated_at'], 'verbose_name': 'Реквизит пользователя', 'verbose_name_plural': 'Реквизиты пользователя'},
        ),
    ]
