# Generated by Django 5.0.6 on 2024-06-25 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_advertiseinfo_options_alter_passport_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertiseinfo',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Пакет рекламной информации', 'verbose_name_plural': 'Пакеты рекламной информации'},
        ),
        migrations.AlterModelOptions(
            name='passport',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Паспорт', 'verbose_name_plural': 'Паспорта'},
        ),
        migrations.AlterModelOptions(
            name='userrequisites',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Реквизит пользователя', 'verbose_name_plural': 'Реквизиты пользователя'},
        ),
    ]
