# Generated by Django 5.0.6 on 2024-07-09 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passport',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Паспорт пользователя', 'verbose_name_plural': 'Паспорта пользователей'},
        ),
    ]
