name: Deploy to Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          echo "Deploying to server..."
          ssh -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} "
            cd /path/to/your/project && \  
            git fetch origin main && \
            git reset --hard origin/main && \
            docker compose -f docker-compose-prod.yaml down && \
            docker compose -f docker-compose-prod.yaml up -d --build
          "
          echo "Deployment complete..."
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
